### ISSUE TITLE
Make it easier to remove Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [h5bp/create-html5-boilerplate#103]
**I'm submitting a ...**

- [X] feature request

## Notes

It seems a little crude to have to remove Google Analytics 'snippets' from various pages prior to using this boilerplate. As someone who wishes to avoid Google Analytics, I feel like I'm fighting against the template. Please consider an easy flag / import to disable this.

**Comment by roblarsen** [comment]
FWIW, you only have to remove it from one page (dist/index.html) but we could add it to the create script easily enough. We would have no mechanism at present to add it to the main project (there are multiple ways to install the main project)

**Comment by roblarsen** [comment]
I killed it with fire in the main project. It's like magic.
