### ISSUE TITLE
Document Development Process

### ISSUE THREAD

**Issue by roblarsen** [h5bp/create-html5-boilerplate#14]
@vltansky Can you write up how to develop this? I'm going to try to enlist some help testing it since I just ran into some issues testing it myself and if people decide they want to help fix stuff I'd like to be able to point them in the right direction. We can add a new section to the Readme.

**Comment by vltansky** [comment]
Not sure what to write.
Generally there are two main files. `cli.js` and `tests/test.js`.
And `index.js` that just imports and run `cli.js`.

**Comment by roblarsen** [comment]
How do you set up your environment so that you can develop locally. Simply that. Make a PR with the steps to be able to run and test this locally and I'll help polish it if anything is unclear (I'll end up testing it myself)
