### ISSUE TITLE
Update `package-lock.json`

### ISSUE THREAD

**Issue by coliff** [h5bp/create-html5-boilerplate#282]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

The `package-lock.json` file was created with an old version of npm. Should fix that (update to lockfile version v2).

**Comment by vltansky** [comment]
`package-lock.json` regenerated in PR https://github.com/h5bp/create-html5-boilerplate/pull/283
