### ISSUE TITLE
Update branch name in release config?

### ISSUE THREAD

**Issue by coliff** [h5bp/create-html5-boilerplate#285]
I think this needs to be 'main' now.

https://github.com/h5bp/create-html5-boilerplate/blob/6d3610f339458617414d4ef9f17cedfe13dee0cf/.releaserc#L2

**Comment by coliff** [comment]
I'm not too familiar with that setup - but do we need to remove 'next' from there too?

**Comment by vltansky** [comment]
I don't remember how it works, but `next` branch probably should trigger the release of `next` tag to npm (e.g `create-html5-boilerplate@next`).
