### ISSUE TITLE
Publish html5-boilerplate to npm

### ISSUE THREAD

**Issue by vltansky** [h5bp/create-html5-boilerplate#357]
Looks like last time it was published 3 years ago. Its still parcel 1 there, although i can see its replaces by webpack.
As a result create-html5-boilerplate downloads old version

**Comment by roblarsen** [comment]
There's been a release queued up for... a couple of years. I am hoping to just get it out the door this month as I'll be slightly less busy.

**Comment by vltansky** [comment]
Ah ok got it
