### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by vltansky** [h5bp/create-html5-boilerplate#4]
I'll write few tests today/tomorrow using jest. Will make pull requests.
Things to test:
* temp folder deleted after copy
* target folder is created
* target folder contains files (maybe to check index.html, css, package.json)
* version downloading feature works
* version downloading works both with 'v' and without (`-r=7.2.0 | v7.2.0 | 7.2`)
* version alias works
* wrong version outputs error

* create coverage using Istanbul (included in jest) and upload to converage.io via github actions

Did I miss something?

**Comment by roblarsen** [comment]
closed via #5
